services:
  - type: web
    name: meli-search-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd ../.. && npm install --legacy-peer-deps && cd apps/backend && npx @nestjs/cli build
    startCommand: node dist/apps/backend/src/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_PREFIX
        value: api/v1
      - key: CORS_ORIGIN
        sync: false
      - key: SWAGGER_ENABLED
        value: true
      - key: SWAGGER_PATH
        value: api
      - key: MOCK_DELAY_MIN
        value: 200
      - key: MOCK_DELAY_MAX
        value: 800
